import React from 'react';
import { Box, Typography, alpha, Container } from '@mui/material';
import { PageLayout, PageHero } from '../components/layout/PageLayout';
import { lunitColors, lunitTypography, lunitRadius } from '../styles/lunitDesignSystem';

const sections = [
  {
    title: '1. Data Controller & Contact Details',
    content: `ClinicalVision AI Ltd ("ClinicalVision", "we", "us", or "our") is the data controller responsible for the personal data processed through our Platform, except where we act as a data processor on behalf of a subscribing healthcare institution (in which case, the institution is the data controller and we process data under their instructions pursuant to a Data Processing Agreement).

**Data Controller**: ClinicalVision AI Ltd
**Address**: 24 Sandymount Avenue, Harrow, Middlesex, UK
**Email**: legal@clinicalvision.ai
**Phone**: +44 7729 773519

If you have any questions about this Privacy Policy, our data practices, or wish to exercise your rights as a data subject, please contact us at legal@clinicalvision.ai.`,
  },
  {
    title: '2. Information We Collect',
    content: `We collect and process the following categories of personal data:

**a) Account & Professional Information**
Data you provide when registering for an account or managing your profile:
• Full name, email address, professional role, and job title
• Professional credentials and registration numbers (e.g., GMC number)
• Organisation name, department, and institutional affiliation
• Account authentication credentials

**b) Patient & Clinical Data (Special Category Data)**
Data uploaded or entered by Authorised Users in the course of clinical use:
• Medical images (mammograms and associated DICOM metadata, including study identifiers, modality, laterality, and acquisition parameters)
• Patient demographics (patient ID, name, date of birth, age, sex)
• Clinical history, findings, measurements, and assessment data
• BI-RADS classifications, clinical narratives, and structured reports

**⚠️ Important**: Patient medical imaging data and clinical information constitute special category data (health data) under Article 9 of UK GDPR. We apply enhanced protections and strict access controls to all such data.

**c) AI Analysis Data**
Data generated by the Platform's AI models during use:
• Classification predictions (benign/malignant) and confidence scores
• Uncertainty metrics (epistemic uncertainty, predictive entropy, mutual information)
• Attention heatmaps, LIME explanations, SHAP attributions, and Integrated Gradients outputs
• Suspicious region detections with bounding box coordinates and attention scores
• Automated BI-RADS assessments and clinical narrative drafts

**d) Usage & Technical Data**
Data collected automatically when you interact with the Platform:
• Session data, feature usage patterns, and workflow interactions
• Browser type, operating system, device information, and screen resolution
• IP address, access timestamps, and referring URLs
• Error logs, performance metrics, and diagnostic data

**e) Communications Data**
Data from your interactions with our support and sales teams:
• Contact form submissions, support tickets, and email correspondence
• Feedback, feature requests, and survey responses`,
  },
  {
    title: '3. Lawful Basis for Processing',
    content: `We process personal data on the following lawful bases under UK GDPR:

| **Data Category** | **Lawful Basis** | **Details** |
|---|---|---|
| Account information | **Contract performance** (Art. 6(1)(b)) | Necessary to provide the Platform services you have subscribed to |
| Patient & clinical data | **Substantial public interest** (Art. 9(2)(h) & Sch. 1, Pt. 1, Para. 2 DPA 2018) | Processing of health data necessary for the provision of healthcare and medical diagnosis by qualified health professionals |
| AI analysis data | **Contract performance** (Art. 6(1)(b)) | Core service delivery — generating AI-assisted analysis outputs |
| Usage & technical data | **Legitimate interests** (Art. 6(1)(f)) | Platform security, performance monitoring, and service improvement |
| Communications data | **Legitimate interests** (Art. 6(1)(f)) | Responding to your enquiries and improving our services |
| Marketing (if opted in) | **Consent** (Art. 6(1)(a)) | Only with your explicit opt-in consent, withdrawable at any time |

**Special Category Data (Health Data)**
We process health data under Article 9(2)(h) of UK GDPR — processing is necessary for the purposes of preventive or occupational medicine, medical diagnosis, the provision of health or social care, or the management of health or social care systems. This processing is carried out by or under the responsibility of a professional subject to the obligation of professional secrecy.

Where we act as a data processor for a healthcare institution, the lawful basis for processing patient data is determined by the institution as data controller.`,
  },
  {
    title: '4. How We Use Your Information',
    content: `We use the information we collect for the following purposes:

**Service Delivery**
• Providing, maintaining, and operating the ClinicalVision AI Platform
• Processing and analysing medical images using our AI models to generate clinical decision support outputs
• Generating structured reports, BI-RADS assessments, and clinical narratives
• Managing clinical workflows, case tracking, and worklist prioritisation
• Authenticating users and enforcing access controls

**Service Improvement**
• Monitoring Platform performance, reliability, and availability
• Identifying and resolving technical issues, bugs, and errors
• Analysing usage patterns (in aggregate and anonymised form) to improve features and user experience
• Conducting internal research using fully de-identified and aggregated data to enhance AI model accuracy

**Communication & Support**
• Responding to your support requests, questions, and feedback
• Sending essential service notifications (e.g., maintenance windows, security alerts, policy updates)
• Providing training materials and onboarding assistance

**Legal & Compliance**
• Complying with applicable laws, regulations, and professional standards
• Maintaining audit trails as required by healthcare regulations
• Detecting, preventing, and responding to security incidents, fraud, or abuse
• Responding to lawful requests from regulatory authorities or courts

**We do not**: sell, rent, lease, or trade personal data or patient Clinical Content to any third party for their marketing or commercial purposes.`,
  },
  {
    title: '5. Data Security & Technical Measures',
    content: `We implement comprehensive technical and organisational measures to protect personal data against unauthorised access, alteration, disclosure, or destruction:

**Encryption**
• All data in transit is protected using TLS 1.3 with strong cipher suites
• All data at rest is encrypted using AES-256 encryption
• Database connections are encrypted end-to-end

**Access Controls**
• Role-based access control (RBAC) limits data access to authorised personnel based on their role and clinical need
• Multi-factor authentication (MFA) is supported for all user accounts
• Session management with automatic timeout and secure token handling

**Infrastructure Security**
• Application hosted on enterprise-grade cloud infrastructure with comprehensive security controls
• Network segmentation, firewalls, and intrusion detection systems
• Regular vulnerability scanning and penetration testing by independent security assessors

**Audit & Monitoring**
• Comprehensive audit logging of all data access, modifications, and clinical actions
• Real-time security monitoring and automated alerting for anomalous activity
• Audit logs are immutable and retained in accordance with healthcare regulatory requirements

**Organisational Measures**
• Staff undergo regular data protection and information security training
• Access to personal data is restricted to personnel who require it for their role
• Confidentiality obligations are included in all employment and contractor agreements
• Incident response procedures are documented, tested, and regularly reviewed`,
  },
  {
    title: '6. Data Retention',
    content: `We retain personal data only for as long as necessary to fulfil the purposes for which it was collected, or as required by applicable law:

| **Data Category** | **Retention Period** | **Rationale** |
|---|---|---|
| Account data | Duration of account plus 7 years | Contractual records retention and regulatory compliance |
| Patient & clinical data | 90 days from analysis (default) | Operational necessity; extended retention available by agreement |
| AI analysis outputs | 90 days from generation (default) | Linked to clinical data retention; configurable per institution |
| Audit logs | 7 years minimum | Healthcare regulatory requirements and legal compliance |
| Usage & technical data | 24 months | Service improvement and security monitoring |
| Communications data | 3 years | Support history and dispute resolution |
| De-identified aggregate data | Indefinitely | Statistical analysis and AI model improvement (contains no personal data) |

**Institutional Data Controllers**: Where we act as a data processor, retention periods are determined by the data controller's policies and our Data Processing Agreement.

**Deletion**: Upon account termination or at your request, personal data will be securely deleted or anonymised within 30 days, except where retention is required by law. Secure deletion is performed using industry-standard data sanitisation methods.

You may request early deletion of your data at any time by contacting legal@clinicalvision.ai, subject to applicable legal retention obligations.`,
  },
  {
    title: '7. Data Sharing & Third Parties',
    content: `We do not sell your personal data. We may share personal data with the following categories of recipients, solely for the purposes described in this Policy:

**Service Providers & Sub-processors**
• Cloud infrastructure providers hosting the Platform (subject to appropriate data processing agreements)
• Email delivery and communication service providers
• Analytics and monitoring tools (processing anonymised or aggregated data only)
• Payment processors for subscription billing (PCI DSS compliant)

All sub-processors are:
• Vetted for their data protection and security practices before engagement
• Bound by written data processing agreements incorporating UK GDPR-compliant terms
• Subject to ongoing monitoring and periodic review

**Legal & Regulatory Disclosure**
We may disclose personal data where required by:
• Applicable law, regulation, or legal process
• A binding order or request from a court, tribunal, or regulatory authority
• The need to protect our legal rights, safety, or property
• A legitimate investigation into suspected fraud, security threats, or illegal activity

**Healthcare Institution (Data Controller)**
Where we act as a data processor, we may disclose data to the subscribing institution in accordance with our Data Processing Agreement and their instructions.

**Business Transfers**
In the event of a merger, acquisition, reorganisation, or sale of assets, personal data may be transferred to the successor entity. We will notify affected users and ensure the successor is bound by equivalent data protection obligations.

**With Your Consent**
We may share data with third parties where you have given explicit, informed consent. You may withdraw consent at any time.`,
  },
  {
    title: '8. International Data Transfers',
    content: `ClinicalVision AI Ltd is based in the United Kingdom. Where we transfer personal data outside the UK or the European Economic Area (EEA), we ensure that appropriate safeguards are in place in accordance with UK GDPR and, where applicable, EU GDPR:

**Transfer Mechanisms**
• **UK International Data Transfer Agreement (IDTA)** or **UK Addendum to the EU Standard Contractual Clauses** — used for transfers to countries without an adequacy decision
• **Adequacy Decisions** — the UK Secretary of State has determined that certain countries provide an adequate level of data protection; transfers to these countries do not require additional safeguards
• **Supplementary Measures** — where necessary, we implement additional technical, contractual, and organisational measures (e.g., encryption, pseudonymisation, access restrictions) to ensure data protection standards are maintained

**Transfer Impact Assessments**
We conduct transfer impact assessments for all international transfers to evaluate the level of protection in the recipient country and determine whether supplementary measures are required.

You may request information about the specific safeguards applied to international transfers of your data by contacting us at legal@clinicalvision.ai.`,
  },
  {
    title: '9. Your Data Subject Rights',
    content: `Under UK GDPR, you have the following rights in relation to your personal data. These rights are not absolute and may be subject to exceptions:

**Right of Access (Article 15)**
You have the right to request confirmation of whether we process your personal data and, if so, to receive a copy of that data along with supplementary information about how it is processed.

**Right to Rectification (Article 16)**
You have the right to request correction of inaccurate personal data and completion of incomplete data.

**Right to Erasure (Article 17)**
You have the right to request deletion of your personal data where it is no longer necessary for the purposes for which it was collected, where you withdraw consent, or where processing is unlawful. This right is subject to legal retention obligations.

**Right to Restriction of Processing (Article 18)**
You have the right to request restriction of processing in certain circumstances, such as while we verify the accuracy of contested data.

**Right to Data Portability (Article 20)**
You have the right to receive your personal data in a structured, commonly used, and machine-readable format, and to transmit it to another controller where technically feasible.

**Right to Object (Article 21)**
You have the right to object to processing based on legitimate interests. We will cease processing unless we demonstrate compelling legitimate grounds that override your interests.

**Rights Related to Automated Decision-Making (Article 22)**
The Platform provides AI-generated decision support outputs. These outputs are not used for automated decision-making with legal or similarly significant effects — all clinical decisions are made by qualified healthcare professionals. You have the right to request human review of any AI Output.

**How to Exercise Your Rights**
To exercise any of these rights, please contact us at legal@clinicalvision.ai or write to us at the address above. We will respond to your request within one month, as required by UK GDPR. In complex cases, we may extend this period by up to two further months, and we will inform you of any such extension.

**Right to Lodge a Complaint**
If you are dissatisfied with our handling of your data or our response to your request, you have the right to lodge a complaint with the Information Commissioner's Office (ICO):

**Information Commissioner's Office**
Website: https://ico.org.uk
Telephone: 0303 123 1113
Email: icocasework@ico.org.uk`,
  },
  {
    title: '10. Cookies & Tracking Technologies',
    content: `The Platform uses cookies and similar technologies for the following purposes:

**Strictly Necessary Cookies**
Required for the Platform to function correctly. These include session management cookies, authentication tokens, and security cookies. These cookies cannot be disabled.

**Functional Cookies**
Used to remember your preferences and settings (e.g., workflow mode, display preferences, last-used filters). These enhance your experience but are not essential.

**Analytics Cookies**
Used to collect anonymised, aggregated information about how the Platform is used, including pages visited, features used, and session duration. This data helps us improve the Platform. Analytics cookies are only set with your consent.

We do not use advertising or tracking cookies. We do not permit third-party advertising networks to place cookies through the Platform.

You can manage your cookie preferences through the Platform's settings. For more information, please refer to our Cookie Policy (available within the Platform) or contact legal@clinicalvision.ai.`,
  },
  {
    title: '11. Children\'s Privacy',
    content: `The ClinicalVision Platform is designed for use by qualified healthcare professionals and is not directed at individuals under the age of 18. We do not knowingly collect personal data from children.

The Platform may process medical imaging data of patients who are under 18, where such processing is carried out by or under the responsibility of a healthcare professional for the purposes of medical diagnosis and healthcare provision, in accordance with Article 9(2)(h) of UK GDPR. In such cases, the data controller (the healthcare institution) is responsible for ensuring appropriate lawful basis and safeguards.

If we become aware that we have inadvertently collected personal data from a child without appropriate authorisation, we will take prompt steps to delete that information.`,
  },
  {
    title: '12. AI-Specific Privacy Considerations',
    content: `As an AI-powered medical device, ClinicalVision processes personal data in ways that require specific transparency:

**AI Model Training**
• Our production AI models were trained on publicly available, de-identified medical imaging datasets (e.g., CBIS-DDSM). No patient-identifiable data from Platform users has been used to train our models without explicit institutional consent and appropriate ethical approval.
• If your institution opts in to a model improvement programme, data will be fully de-identified before use, in accordance with the ICO's guidance on anonymisation and a formal Data Processing Agreement.

**Automated Processing**
• The Platform uses automated processing to generate AI Outputs (e.g., classifications, confidence scores, attention heatmaps). These outputs are provided as decision support tools and are not used for automated decision-making with legal or similarly significant effects.
• All AI Outputs are subject to review by a qualified healthcare professional before any clinical action is taken.

**Explainability**
• The Platform provides explainable AI tools (Grad-CAM, LIME, SHAP, Integrated Gradients) to enable clinicians to understand and verify the basis of AI predictions. This supports the UK GDPR principle of transparency and the right to meaningful information about the logic involved in automated processing.

**Bias & Fairness Monitoring**
• We monitor AI model performance across demographic groups to identify and mitigate potential bias. Fairness metrics (demographic parity, equalised odds) are reported in alignment with the NIST AI Risk Management Framework and MHRA guidance on AI as a medical device.

**Data Minimisation**
• AI analysis is performed using the minimum data necessary. Images are processed for analysis and results are returned to the user; raw image data is not retained beyond the configured retention period.`,
  },
  {
    title: '13. Changes to This Policy',
    content: `We may update this Privacy Policy from time to time to reflect changes in our practices, legal requirements, or regulatory guidance. We will notify you of material changes through one or more of the following:

• Posting the updated policy on this page with a revised "Last updated" date
• Sending an email notification to the registered email address associated with your account
• Displaying a prominent notice within the Platform

Material changes will take effect no earlier than 30 days after notification. Your continued use of the Platform after the effective date constitutes acceptance of the updated policy. If you do not agree with the changes, you should discontinue use of the Platform and contact us to discuss your options.

We recommend reviewing this policy periodically. Previous versions of this policy are available upon request.`,
  },
  {
    title: '14. Contact Us',
    content: `If you have questions about this Privacy Policy, our data practices, or wish to exercise your data subject rights:

**ClinicalVision AI Ltd**
**Email**: legal@clinicalvision.ai
**Address**: 24 Sandymount Avenue, Harrow, Middlesex, UK
**Phone**: +44 7729 773519

**Supervisory Authority**
You have the right to lodge a complaint with the UK's supervisory authority:

**Information Commissioner's Office (ICO)**
Wycliffe House, Water Lane, Wilmslow, Cheshire, SK9 5AF
Website: https://ico.org.uk
Telephone: 0303 123 1113

For EU/EEA residents, you may also contact your local supervisory authority.`,
  },
];

const PrivacyPage: React.FC = () => {
  return (
    <PageLayout>
      {/* Hero */}
      <PageHero
        label="Legal"
        title="Privacy Policy"
        subtitle="Last updated: March 2026"
      />

      {/* Content */}
      <Box sx={{ py: { xs: '60px', md: '80px' }, bgcolor: lunitColors.white }}>
        <Container maxWidth="lg">
        <Box sx={{ maxWidth: '800px', mx: 'auto' }}>
          <Box
            sx={{
              p: 4,
              mb: 4,
              borderRadius: lunitRadius['2xl'],
              bgcolor: alpha(lunitColors.teal, 0.08),
              borderLeft: `4px solid ${lunitColors.teal}`,
            }}
          >
            <Typography
              sx={{
                fontFamily: lunitTypography.fontFamilyBody,
                fontSize: '15px',
                fontWeight: 400,
                color: lunitColors.text,
                lineHeight: 1.8,
              }}
            >
              At ClinicalVision AI Ltd, protecting your privacy and the confidentiality of patient health information is fundamental to everything we do. This Privacy Policy explains how we collect, use, store, share, and protect personal data when you use our AI-powered clinical decision support platform. We are committed to full compliance with the UK General Data Protection Regulation (UK GDPR), the Data Protection Act 2018, and all applicable data protection legislation. Where we process patient health data, we apply the highest standards of care as required for special category data under Article 9 of UK GDPR.
            </Typography>
          </Box>

          {sections.map((section, idx) => (
            <Box key={idx} sx={{ mb: 5 }}>
              <Typography
                sx={{
                  fontFamily: lunitTypography.fontFamilyHeading,
                  fontSize: '22px',
                  fontWeight: 500,
                  color: lunitColors.headingColor,
                  mb: 2,
                }}
              >
                {section.title}
              </Typography>
              <Typography
                component="div"
                sx={{
                  fontFamily: lunitTypography.fontFamilyBody,
                  fontSize: '15px',
                  fontWeight: 300,
                  color: lunitColors.text,
                  lineHeight: 1.9,
                  whiteSpace: 'pre-line',
                  '& strong': {
                    fontWeight: 500,
                    color: lunitColors.headingColor,
                  },
                }}
              >
                {section.content}
              </Typography>
            </Box>
          ))}
        </Box>
        </Container>
      </Box>
    </PageLayout>
  );
};

export default PrivacyPage;
