import React from 'react';
import { Box, Typography, alpha, Container } from '@mui/material';
import { PageLayout, PageHero } from '../components/layout/PageLayout';
import { lunitColors, lunitTypography, lunitRadius } from '../styles/lunitDesignSystem';

const sections = [
  {
    title: '1. Definitions & Interpretation',
    content: `In these Terms of Use, the following definitions apply unless the context requires otherwise:

• **"ClinicalVision"**, **"we"**, **"us"**, or **"our"** refers to ClinicalVision AI Ltd, a company registered in England and Wales, with its registered office at 24 Sandymount Avenue, Harrow, Middlesex, UK.
• **"Platform"** means the ClinicalVision AI software application, including all associated services, APIs, documentation, and updates.
• **"User"**, **"you"**, or **"your"** means any individual or organisation that accesses or uses the Platform, including Authorised Users acting on behalf of a subscribing institution.
• **"Authorised User"** means a healthcare professional, administrator, or other individual granted access credentials under an institutional subscription.
• **"Clinical Content"** means all medical images, patient data, reports, findings, and related clinical information processed through the Platform.
• **"AI Output"** means any analysis results, confidence scores, heatmaps, risk assessments, BI-RADS classifications, or other outputs generated by the Platform's artificial intelligence models.
• **"SaMD"** means Software as a Medical Device, as defined under the UK Medical Devices Regulations 2002 (as amended) and EU Regulation 2017/745 (MDR).`,
  },
  {
    title: '2. Acceptance of Terms',
    content: `By accessing or using the Platform, you confirm that you have read, understood, and agree to be bound by these Terms of Use, our Privacy Policy, and all applicable laws and regulations.

If you are accepting these Terms on behalf of a healthcare institution, hospital trust, or other organisation, you represent and warrant that you have the authority to bind that organisation to these Terms. In such cases, "you" and "your" shall refer to that organisation.

If you do not agree with any provision of these Terms, you must not access or use the Platform. Continued use of the Platform following any amendment to these Terms constitutes acceptance of the modified Terms.`,
  },
  {
    title: '3. Description of Services',
    content: `ClinicalVision provides an AI-powered clinical decision support platform for medical imaging analysis. The Platform offers:

• **AI-Assisted Image Analysis** — Deep learning classification of mammographic images using ensemble neural network architectures, returning benign/malignant predictions with calibrated confidence scores
• **Explainable AI (XAI)** — Visual explanation tools including Grad-CAM, Grad-CAM++, LIME, SHAP, and Integrated Gradients, enabling clinicians to understand and verify AI reasoning
• **Uncertainty Quantification** — Monte Carlo Dropout-based epistemic uncertainty estimation, predictive entropy, and mutual information metrics to flag cases requiring additional clinical review
• **BI-RADS Structured Reporting** — Automated BI-RADS 0–6 classification (including 4A/4B/4C subdivisions), clinical narrative generation, and PDF report export with full audit trail
• **DICOM Integration** — Native DICOM image handling with metadata extraction and clinical-grade image viewing
• **Clinical Workflow Engine** — Structured workflow supporting image upload, AI analysis, patient demographics, measurements, clinical assessment, reporting, and case finalisation
• **AI Fairness Monitoring** — Demographic parity and equalised odds monitoring across patient demographics, aligned with NIST AI Risk Management Framework
• **Case Management** — Priority-scored worklist, case tracking, historical archive, and multi-user workflow support

**CRITICAL NOTICE**: The Platform is classified as a clinical decision support tool and is intended solely to assist — never to replace — qualified healthcare professionals in their clinical judgement. All diagnostic and treatment decisions remain the exclusive responsibility of appropriately licensed and qualified medical practitioners. AI Outputs are supplementary and must be independently verified by the treating clinician before any clinical action is taken.`,
  },
  {
    title: '4. Eligibility & User Accounts',
    content: `**Eligibility Requirements**
To register for and use the Platform, you must:

• Be at least 18 years of age and have the legal capacity to enter into binding agreements
• Hold appropriate professional qualifications and registration for the intended clinical use (e.g., GMC registration for radiologists in the UK, or equivalent in your jurisdiction)
• Be acting within the scope of your professional competence and in accordance with your institution's policies
• Have received adequate training on the Platform's capabilities and limitations

**Account Obligations**
As an account holder, you are responsible for:

• Providing accurate, complete, and current registration information, including valid professional credentials
• Maintaining the confidentiality of your account credentials and preventing unauthorised access
• All activities that occur under your account, whether or not you authorised them
• Notifying us immediately at legal@clinicalvision.ai of any suspected unauthorised access or security breach
• Ensuring that your use complies with all applicable professional standards and institutional policies

We reserve the right to verify professional credentials, suspend accounts pending verification, and terminate accounts that violate these Terms or pose a risk to patient safety.`,
  },
  {
    title: '5. Intended Use & Clinical Limitations',
    content: `**Intended Use**
ClinicalVision is intended for use by qualified healthcare professionals as a computer-aided detection (CAD) and clinical decision support tool in the analysis of mammographic images for breast cancer screening and diagnosis.

**Clinical Limitations — Please Read Carefully**

• The Platform provides AI-generated decision support, not final diagnoses. AI Outputs must never be treated as a substitute for professional clinical judgement.
• All AI Outputs must be reviewed, verified, and clinically correlated by a qualified medical professional before any diagnostic or treatment decision is made.
• The Platform must not be used as the sole basis for clinical decisions, patient management, or treatment planning.
• AI model performance may vary based on image quality, acquisition parameters, patient demographics, breast density, implant presence, and other clinical factors.
• The Platform is not intended for use in emergency, urgent, or time-critical clinical scenarios.
• Historical performance metrics do not guarantee future accuracy. AI models are statistical in nature and inherently subject to error.
• The Platform has been developed and validated using specific datasets and populations. Performance on populations not represented in training data may differ.
• Users should report any suspected errors, unexpected behaviours, or adverse events to legal@clinicalvision.ai promptly.

**Regulatory Status**
The Platform is developed following IEC 62304:2006+AMD1:2015 (Medical device software lifecycle), ISO 14971:2019 (Risk management), and aligned with ISO 13485:2016 (Quality management systems). ClinicalVision is an emerging medical technology company actively preparing for regulatory submissions. The Platform has not yet received regulatory clearance or approval from the MHRA, FDA, or any EU Notified Body. Current regulatory pathway status is available upon request.`,
  },
  {
    title: '6. Data Protection & Privacy',
    content: `Your use of the Platform is governed by our Privacy Policy, which forms an integral part of these Terms. Key principles:

• We process Clinical Content and personal data in accordance with the UK General Data Protection Regulation (UK GDPR), the Data Protection Act 2018, and, where applicable, the EU General Data Protection Regulation (EU GDPR).
• Medical imaging data constitutes special category data under Article 9 of UK GDPR. We process such data on the lawful bases of explicit consent, the provision of healthcare, and/or substantial public interest.
• All data is encrypted in transit using TLS 1.3 and at rest using AES-256 encryption.
• We maintain technical and organisational measures appropriate to the sensitivity of the data processed.
• For institutional customers, we execute Data Processing Agreements (DPAs) that detail our obligations as a data processor.
• You retain full ownership of all patient data and Clinical Content uploaded to the Platform.
• We do not sell, lease, or trade personal data or Clinical Content to third parties.

For full details on data collection, processing, retention, international transfers, and your data subject rights, please refer to our Privacy Policy.`,
  },
  {
    title: '7. Intellectual Property',
    content: `**Our Intellectual Property**
ClinicalVision AI Ltd retains all rights, title, and interest in:

• The Platform, including all AI models, algorithms, neural network architectures, and trained weights
• All software, source code, object code, and technical documentation
• Trademarks, logos, brand elements, and trade dress
• Training methodologies, calibration techniques, and proprietary processes
• Aggregated, de-identified statistical insights derived from Platform usage (which do not contain or reveal any patient-identifiable information)

**Your Intellectual Property**
You retain all rights, title, and interest in:

• All patient data, medical images, and Clinical Content uploaded to the Platform
• Clinical reports, assessments, and documentation you create using the Platform
• Your institution's proprietary information and organisational data

**Licence Grant**
You grant us a limited, non-exclusive, non-transferable licence to process your Clinical Content solely for the purpose of providing the Platform's services to you. This licence terminates upon termination of your account, subject to applicable data retention requirements.`,
  },
  {
    title: '8. Subscription, Fees & Payment',
    content: `• Access to the Platform is provided on a subscription basis. Subscription plans, pricing, and included features are detailed on our website and in your individual or institutional service agreement.
• Subscription fees are invoiced in advance on a monthly or annual billing cycle, as selected at the time of purchase.
• All fees are quoted in British Pounds Sterling (GBP) unless otherwise agreed in writing. VAT shall be applied at the prevailing rate where applicable.
• We reserve the right to adjust pricing with not less than 30 days' prior written notice. Price changes take effect at the start of the next billing period.
• Failure to pay invoiced amounts within 30 days may result in suspension of access to the Platform. Continued non-payment may result in termination of the subscription.
• Refunds are provided only where required by applicable law or as expressly stated in your service agreement. Annual prepayments are non-refundable except as required by the Consumer Rights Act 2015.
• Enterprise and institutional agreements may include bespoke billing, volume-based pricing, and service level commitments.`,
  },
  {
    title: '9. Acceptable Use',
    content: `You agree not to:

• Use the Platform for any purpose other than its intended clinical decision support function
• Attempt to reverse-engineer, decompile, disassemble, or derive the source code or algorithms of the Platform or its AI models
• Use the Platform to process data in violation of applicable data protection laws, patient consent requirements, or professional ethical obligations
• Share account credentials or permit unauthorised individuals to access the Platform
• Upload content that infringes third-party intellectual property rights or contains malicious code
• Attempt to circumvent security measures, access controls, or usage limitations
• Use automated scripts, bots, or scraping tools to interact with the Platform
• Use AI Outputs for purposes beyond clinical decision support, including but not limited to insurance underwriting, employment screening, or marketing
• Misrepresent AI Outputs as independent clinical diagnoses or present them to patients without appropriate professional context

Violation of these provisions may result in immediate suspension or termination of your account and may be reported to relevant professional regulatory bodies.`,
  },
  {
    title: '10. Warranty Disclaimer',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

The Platform and all AI Outputs are provided on an "AS IS" and "AS AVAILABLE" basis, without warranties of any kind, whether express, implied, or statutory, including but not limited to:

• IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT
• WARRANTIES AS TO THE ACCURACY, COMPLETENESS, RELIABILITY, OR TIMELINESS OF AI OUTPUTS
• WARRANTIES THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM VULNERABILITIES
• WARRANTIES THAT AI OUTPUTS WILL ACHIEVE ANY PARTICULAR CLINICAL OUTCOME

AI models are statistical tools that produce probabilistic outputs. No AI system can guarantee diagnostic accuracy. The Platform is designed to assist clinical decision-making, and all outputs are subject to the professional judgement of qualified healthcare practitioners.

Nothing in these Terms excludes or limits liability that cannot lawfully be excluded or limited under English law, including liability for death or personal injury caused by negligence, fraud, or fraudulent misrepresentation.`,
  },
  {
    title: '11. Limitation of Liability',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

• ClinicalVision AI Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, loss of data, loss of goodwill, business interruption, or clinical outcomes arising from the use of or inability to use the Platform.
• Our aggregate liability for all claims arising out of or in connection with these Terms shall not exceed the total fees paid by you to ClinicalVision AI Ltd in the twelve (12) months immediately preceding the event giving rise to the claim.
• We are not liable for clinical decisions, diagnoses, or treatment plans made by healthcare professionals using the Platform. Clinical responsibility rests solely with the treating practitioner.
• We are not liable for failures, errors, or degradation caused by third-party systems, integrations, network connectivity, or factors outside our reasonable control.

Nothing in these Terms shall exclude or limit our liability for: (a) death or personal injury caused by our negligence; (b) fraud or fraudulent misrepresentation; or (c) any other liability that cannot lawfully be excluded or limited under English law.`,
  },
  {
    title: '12. Indemnification',
    content: `You agree to indemnify, defend, and hold harmless ClinicalVision AI Ltd, its officers, directors, employees, agents, and licensors from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from:

• Your use of the Platform or any AI Outputs
• Your breach of these Terms or any applicable law or regulation
• Your violation of any third-party rights, including patient privacy rights
• Clinical decisions, diagnoses, or treatment actions taken using or informed by AI Outputs
• Your failure to comply with applicable professional standards, institutional policies, or regulatory requirements
• Any claim by a patient or third party arising from your clinical practice involving the Platform

This indemnification obligation shall survive the termination or expiration of these Terms.`,
  },
  {
    title: '13. Termination',
    content: `**Termination by You**
You may terminate your account at any time by providing written notice to legal@clinicalvision.ai. Prepaid subscription fees are non-refundable except as required by applicable law.

**Termination by Us**
We may suspend or terminate your access to the Platform immediately if:

• You breach any material provision of these Terms
• Your use of the Platform poses a risk to patient safety, data security, or system integrity
• We are required to do so by law, regulation, or order of a competent authority
• You fail to pay applicable fees within the specified payment terms
• Your professional credentials are suspended, revoked, or subject to regulatory investigation

**Effects of Termination**
Upon termination:
• Your right to access and use the Platform ceases immediately
• We will provide you with access to export your Clinical Content for a period of 30 days following termination, after which it will be securely deleted
• Provisions that by their nature should survive termination (including intellectual property, limitation of liability, indemnification, and governing law) shall continue in full force and effect
• We will retain audit logs and compliance records as required by applicable law`,
  },
  {
    title: '14. Governing Law & Dispute Resolution',
    content: `These Terms shall be governed by and construed in accordance with the laws of England and Wales.

**Dispute Resolution**
The parties agree to attempt to resolve any dispute arising out of or in connection with these Terms through good-faith negotiation in the first instance.

If a dispute cannot be resolved through negotiation within 30 days, either party may refer the matter to mediation in accordance with the Centre for Effective Dispute Resolution (CEDR) Model Mediation Procedure.

If mediation is unsuccessful, the courts of England and Wales shall have exclusive jurisdiction to settle the dispute, except that either party may seek interim injunctive relief in any court of competent jurisdiction.

**Regulatory Complaints**
If you believe the Platform has caused or contributed to a patient safety incident, please report it to us immediately at legal@clinicalvision.ai and, where appropriate, to the Medicines and Healthcare products Regulatory Agency (MHRA) via their Yellow Card reporting scheme.`,
  },
  {
    title: '15. Changes to Terms',
    content: `We reserve the right to amend these Terms at any time. We will provide reasonable advance notice of material changes through one or more of the following:

• Email notification to the registered email address associated with your account
• Prominent notice displayed within the Platform
• Updated publication on our website with a revised "Last updated" date

Material changes will take effect no earlier than 30 days after notification. Your continued use of the Platform after the effective date of any amendment constitutes acceptance of the modified Terms. If you do not agree to the modified Terms, you must discontinue use of the Platform and terminate your account.

We recommend reviewing these Terms periodically to remain informed of any updates.`,
  },
  {
    title: '16. General Provisions',
    content: `**Entire Agreement**: These Terms, together with our Privacy Policy and any applicable service agreement, constitute the entire agreement between you and ClinicalVision AI Ltd regarding the Platform and supersede all prior agreements, understandings, and representations.

**Severability**: If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect.

**Waiver**: No failure or delay by either party in exercising any right under these Terms shall constitute a waiver of that right. A waiver of any provision shall not be deemed a waiver of any subsequent breach of the same or any other provision.

**Assignment**: You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations without restriction.

**Force Majeure**: Neither party shall be liable for any failure or delay in performance due to circumstances beyond its reasonable control, including but not limited to natural disasters, pandemics, governmental actions, cyberattacks, or infrastructure failures.

**Third-Party Rights**: These Terms do not confer any rights on any person or party other than the parties to these Terms and their respective successors and permitted assigns, pursuant to the Contracts (Rights of Third Parties) Act 1999.

**Notices**: All formal notices under these Terms shall be in writing and sent to the registered addresses of the parties or, in the case of notices to ClinicalVision AI Ltd, to legal@clinicalvision.ai.`,
  },
  {
    title: '17. Contact Information',
    content: `For questions, concerns, or notices relating to these Terms of Use:

**ClinicalVision AI Ltd**
**Email**: legal@clinicalvision.ai
**Address**: 24 Sandymount Avenue, Harrow, Middlesex, UK
**Phone**: +44 7729 773519

**Regulatory & Safety Reporting**
To report a suspected adverse event, malfunction, or patient safety concern related to the Platform, contact us at legal@clinicalvision.ai or report directly to the MHRA via the Yellow Card scheme at https://yellowcard.mhra.gov.uk.`,
  },
];

const TermsPage: React.FC = () => {
  return (
    <PageLayout>
      {/* Hero */}
      <PageHero
        label="Legal"
        title="Terms of Use"
        subtitle="Last updated: March 2026"
      />

      {/* Content */}
      <Box sx={{ py: { xs: '60px', md: '80px' }, bgcolor: lunitColors.white }}>
        <Container maxWidth="lg">
        <Box sx={{ maxWidth: '800px', mx: 'auto' }}>
          <Box
            sx={{
              p: 4,
              mb: 4,
              borderRadius: lunitRadius['2xl'],
              bgcolor: alpha(lunitColors.teal, 0.08),
              borderLeft: `4px solid ${lunitColors.teal}`,
            }}
          >
            <Typography
              sx={{
                fontFamily: lunitTypography.fontFamilyBody,
                fontSize: '15px',
                fontWeight: 400,
                color: lunitColors.text,
                lineHeight: 1.8,
              }}
            >
              Please read these Terms of Use carefully before using the ClinicalVision AI platform. These Terms constitute a legally binding agreement between you and ClinicalVision AI Ltd. By accessing or using our Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you are using the Platform on behalf of a healthcare institution, you confirm that you are authorised to accept these Terms on its behalf.
            </Typography>
          </Box>

          {sections.map((section, idx) => (
            <Box key={idx} sx={{ mb: 5 }}>
              <Typography
                sx={{
                  fontFamily: lunitTypography.fontFamilyHeading,
                  fontSize: '22px',
                  fontWeight: 500,
                  color: lunitColors.headingColor,
                  mb: 2,
                }}
              >
                {section.title}
              </Typography>
              <Typography
                component="div"
                sx={{
                  fontFamily: lunitTypography.fontFamilyBody,
                  fontSize: '15px',
                  fontWeight: 300,
                  color: lunitColors.text,
                  lineHeight: 1.9,
                  whiteSpace: 'pre-line',
                  '& strong': {
                    fontWeight: 500,
                    color: lunitColors.headingColor,
                  },
                }}
              >
                {section.content}
              </Typography>
            </Box>
          ))}
        </Box>
        </Container>
      </Box>
    </PageLayout>
  );
};

export default TermsPage;
