"""add_dicom_clinical_report_model_version_tables

Revision ID: 1e8539f93b11
Revises: 19898720d33b
Create Date: 2026-01-08 17:09:55.207615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e8539f93b11'
down_revision: Union[str, Sequence[str], None] = '19898720d33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_performance_logs',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.String(), nullable=False),
    sa.Column('measurement_window_days', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('avg_inference_time_ms', sa.Float(), nullable=True),
    sa.Column('feedback_received', sa.Integer(), nullable=True),
    sa.Column('agreement_rate', sa.Float(), nullable=True),
    sa.Column('performance_alert', sa.Boolean(), nullable=True),
    sa.Column('drift_alert', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_logs_id'), 'model_performance_logs', ['id'], unique=True)
    op.create_index(op.f('ix_model_performance_logs_is_deleted'), 'model_performance_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_model_performance_logs_log_date'), 'model_performance_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_model_performance_logs_model_version_id'), 'model_performance_logs', ['model_version_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=True),
    sa.Column('algorithm_type', sa.Enum('CNN', 'ENSEMBLE', 'TRANSFER_LEARNING', 'TRANSFORMER', 'BAYESIAN', 'HYBRID', 'TRADITIONAL_ML', name='algorithmtype'), nullable=False),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('training_date', sa.String(), nullable=True),
    sa.Column('training_duration_hours', sa.Float(), nullable=True),
    sa.Column('training_dataset_size', sa.Integer(), nullable=True),
    sa.Column('training_dataset_version', sa.String(length=50), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subgroup_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_status', sa.Enum('NOT_VALIDATED', 'INTERNAL_VALIDATION', 'EXTERNAL_VALIDATION', 'CLINICAL_VALIDATION', 'FDA_CLEARED', 'FDA_APPROVED', 'CE_MARKED', name='validationstatus'), nullable=False),
    sa.Column('clinical_study_id', sa.String(length=100), nullable=True),
    sa.Column('validation_dataset_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fda_approval_status', sa.String(length=50), nullable=True),
    sa.Column('fda_submission_date', sa.String(), nullable=True),
    sa.Column('fda_clearance_date', sa.String(), nullable=True),
    sa.Column('fda_clearance_number', sa.String(length=50), nullable=True),
    sa.Column('ce_marking', sa.Boolean(), nullable=True),
    sa.Column('ce_marking_date', sa.String(), nullable=True),
    sa.Column('intended_use', sa.Text(), nullable=True),
    sa.Column('indications_for_use', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DEVELOPMENT', 'VALIDATION', 'FDA_SUBMISSION', 'APPROVED', 'ACTIVE', 'DEPRECATED', 'RETIRED', 'RECALLED', name='modelstatus'), nullable=False),
    sa.Column('deployment_environment', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', 'RESEARCH', 'CLINICAL_TRIAL', name='deploymentenvironment'), nullable=True),
    sa.Column('deployment_date', sa.String(), nullable=True),
    sa.Column('deprecation_date', sa.String(), nullable=True),
    sa.Column('retirement_date', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('model_file_path', sa.String(length=500), nullable=True),
    sa.Column('model_file_size_mb', sa.Float(), nullable=True),
    sa.Column('model_checksum', sa.String(length=64), nullable=True),
    sa.Column('preprocessing_pipeline_path', sa.String(length=500), nullable=True),
    sa.Column('config_file_path', sa.String(length=500), nullable=True),
    sa.Column('production_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_drift_detected', sa.Boolean(), nullable=True),
    sa.Column('last_drift_check_date', sa.String(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('known_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('paper_citation', sa.Text(), nullable=True),
    sa.Column('paper_doi', sa.String(length=100), nullable=True),
    sa.Column('fairness_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explainability_method', sa.String(length=100), nullable=True),
    sa.Column('uncertainty_quantification', sa.Boolean(), nullable=True),
    sa.Column('ethics_approval', sa.Boolean(), nullable=True),
    sa.Column('ethics_board', sa.String(length=255), nullable=True),
    sa.Column('ethics_approval_date', sa.String(), nullable=True),
    sa.Column('developed_by', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_hash')
    )
    op.create_index(op.f('ix_model_versions_deployment_date'), 'model_versions', ['deployment_date'], unique=False)
    op.create_index(op.f('ix_model_versions_fda_clearance_number'), 'model_versions', ['fda_clearance_number'], unique=False)
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=True)
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_versions_is_deleted'), 'model_versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_training_date'), 'model_versions', ['training_date'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.create_table('clinical_reports',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=True),
    sa.Column('report_type', sa.Enum('BIRADS', 'NARRATIVE', 'STRUCTURED', 'COMPARISON', 'ADDENDUM', 'CONSULTATION', name='reporttype'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'SIGNED', 'AMENDED', 'DELETED', name='reportstatus'), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impression', sa.Text(), nullable=True),
    sa.Column('clinical_history', sa.Text(), nullable=True),
    sa.Column('technique', sa.Text(), nullable=True),
    sa.Column('comparison', sa.Text(), nullable=True),
    sa.Column('overall_birads', sa.String(length=10), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_interval_months', sa.Integer(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_findings_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_report_id', sa.UUID(), nullable=True),
    sa.Column('amendment_reason', sa.Text(), nullable=True),
    sa.Column('drafted_at', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('signed_at', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('critical_finding', sa.Boolean(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('template_version', sa.String(length=20), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_report_id'], ['clinical_reports.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_reports_author_id'), 'clinical_reports', ['author_id'], unique=False)
    op.create_index(op.f('ix_clinical_reports_critical_finding'), 'clinical_reports', ['critical_finding'], unique=False)
    op.create_index(op.f('ix_clinical_reports_id'), 'clinical_reports', ['id'], unique=True)
    op.create_index(op.f('ix_clinical_reports_is_deleted'), 'clinical_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_clinical_reports_overall_birads'), 'clinical_reports', ['overall_birads'], unique=False)
    op.create_index(op.f('ix_clinical_reports_report_number'), 'clinical_reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_clinical_reports_status'), 'clinical_reports', ['status'], unique=False)
    op.create_index(op.f('ix_clinical_reports_study_id'), 'clinical_reports', ['study_id'], unique=False)
    op.create_table('dicom_metadata',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('sop_class_uid', sa.String(length=255), nullable=True),
    sa.Column('transfer_syntax_uid', sa.Enum('IMPLICIT_VR_LITTLE_ENDIAN', 'EXPLICIT_VR_LITTLE_ENDIAN', 'EXPLICIT_VR_BIG_ENDIAN', 'JPEG_BASELINE', 'JPEG_LOSSLESS', 'JPEG_2000_LOSSLESS', 'RLE_LOSSLESS', name='transfersyntax'), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_birth_date', sa.DateTime(), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=True),
    sa.Column('patient_age', sa.String(length=10), nullable=True),
    sa.Column('patient_weight', sa.Float(), nullable=True),
    sa.Column('study_date', sa.DateTime(), nullable=True),
    sa.Column('study_time', sa.String(length=20), nullable=True),
    sa.Column('referring_physician_name', sa.String(length=255), nullable=True),
    sa.Column('study_description', sa.Text(), nullable=True),
    sa.Column('series_date', sa.DateTime(), nullable=True),
    sa.Column('series_time', sa.String(length=20), nullable=True),
    sa.Column('series_description', sa.Text(), nullable=True),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('body_part_examined', sa.String(length=50), nullable=True),
    sa.Column('patient_position', sa.Enum('HFP', 'HFS', 'HFDR', 'HFDL', 'FFP', 'FFS', 'FFDR', 'FFDL', 'UNKNOWN', name='patientposition'), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_model_name', sa.String(length=255), nullable=True),
    sa.Column('device_serial_number', sa.String(length=255), nullable=True),
    sa.Column('software_versions', sa.String(length=255), nullable=True),
    sa.Column('station_name', sa.String(length=100), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('acquisition_time', sa.String(length=20), nullable=True),
    sa.Column('acquisition_number', sa.Integer(), nullable=True),
    sa.Column('image_type', sa.String(length=255), nullable=True),
    sa.Column('samples_per_pixel', sa.Integer(), nullable=True),
    sa.Column('photometric_interpretation', sa.Enum('MONOCHROME1', 'MONOCHROME2', 'PALETTE_COLOR', 'RGB', 'YBR_FULL', name='photometricinterpretation'), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('bits_allocated', sa.Integer(), nullable=True),
    sa.Column('bits_stored', sa.Integer(), nullable=True),
    sa.Column('high_bit', sa.Integer(), nullable=True),
    sa.Column('pixel_representation', sa.Integer(), nullable=True),
    sa.Column('view_position', sa.String(length=50), nullable=True),
    sa.Column('image_laterality', sa.String(length=10), nullable=True),
    sa.Column('compressed_thickness', sa.Float(), nullable=True),
    sa.Column('compression_force', sa.Float(), nullable=True),
    sa.Column('paddle_description', sa.String(length=255), nullable=True),
    sa.Column('detector_type', sa.String(length=100), nullable=True),
    sa.Column('detector_id', sa.String(length=100), nullable=True),
    sa.Column('exposure_in_uas', sa.Float(), nullable=True),
    sa.Column('kvp', sa.Float(), nullable=True),
    sa.Column('exposure_time', sa.Float(), nullable=True),
    sa.Column('pixel_spacing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imager_pixel_spacing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('window_center', sa.Float(), nullable=True),
    sa.Column('window_width', sa.Float(), nullable=True),
    sa.Column('quality_control_image', sa.String(length=10), nullable=True),
    sa.Column('burn_in_annotation', sa.String(length=10), nullable=True),
    sa.Column('additional_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_dicom_header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anonymized', sa.String(length=10), nullable=False),
    sa.Column('phi_removed', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dicom_metadata_acquisition_date'), 'dicom_metadata', ['acquisition_date'], unique=False)
    op.create_index(op.f('ix_dicom_metadata_id'), 'dicom_metadata', ['id'], unique=True)
    op.create_index(op.f('ix_dicom_metadata_image_id'), 'dicom_metadata', ['image_id'], unique=True)
    op.create_index(op.f('ix_dicom_metadata_is_deleted'), 'dicom_metadata', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dicom_metadata_sop_class_uid'), 'dicom_metadata', ['sop_class_uid'], unique=False)
    op.create_table('report_workflow_history',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'SIGNED', 'AMENDED', 'DELETED', name='reportstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'REVIEWED', 'APPROVED', 'SIGNED', 'AMENDED', 'DELETED', name='reportstatus'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['clinical_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_workflow_history_id'), 'report_workflow_history', ['id'], unique=True)
    op.create_index(op.f('ix_report_workflow_history_is_deleted'), 'report_workflow_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_report_workflow_history_report_id'), 'report_workflow_history', ['report_id'], unique=False)
    op.drop_index(op.f('idx_analyses_explainability_gin'), table_name='analyses', postgresql_using='gin')
    op.drop_index(op.f('idx_analyses_image_prediction'), table_name='analyses')
    op.drop_index(op.f('idx_analyses_roi_gin'), table_name='analyses', postgresql_using='gin')
    op.drop_index(op.f('idx_feedback_annotations_gin'), table_name='feedback', postgresql_using='gin')
    op.drop_index(op.f('idx_feedback_radiologist_date'), table_name='feedback')
    op.drop_index(op.f('idx_images_study_view'), table_name='images')
    op.drop_index(op.f('idx_studies_org_date'), table_name='studies')
    op.drop_index(op.f('idx_users_org_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_org_role'), 'users', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('idx_studies_org_date'), 'studies', ['organization_id', 'study_date'], unique=False)
    op.create_index(op.f('idx_images_study_view'), 'images', ['study_id', 'view_type', 'laterality'], unique=False)
    op.create_index(op.f('idx_feedback_radiologist_date'), 'feedback', ['radiologist_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_feedback_annotations_gin'), 'feedback', ['annotations'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_analyses_roi_gin'), 'analyses', ['roi_coordinates'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_analyses_image_prediction'), 'analyses', ['image_id', 'prediction_class'], unique=False)
    op.create_index(op.f('idx_analyses_explainability_gin'), 'analyses', ['explainability_data'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_report_workflow_history_report_id'), table_name='report_workflow_history')
    op.drop_index(op.f('ix_report_workflow_history_is_deleted'), table_name='report_workflow_history')
    op.drop_index(op.f('ix_report_workflow_history_id'), table_name='report_workflow_history')
    op.drop_table('report_workflow_history')
    op.drop_index(op.f('ix_dicom_metadata_sop_class_uid'), table_name='dicom_metadata')
    op.drop_index(op.f('ix_dicom_metadata_is_deleted'), table_name='dicom_metadata')
    op.drop_index(op.f('ix_dicom_metadata_image_id'), table_name='dicom_metadata')
    op.drop_index(op.f('ix_dicom_metadata_id'), table_name='dicom_metadata')
    op.drop_index(op.f('ix_dicom_metadata_acquisition_date'), table_name='dicom_metadata')
    op.drop_table('dicom_metadata')
    op.drop_index(op.f('ix_clinical_reports_study_id'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_status'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_report_number'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_overall_birads'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_is_deleted'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_id'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_critical_finding'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_author_id'), table_name='clinical_reports')
    op.drop_table('clinical_reports')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_training_date'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_deleted'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_fda_clearance_number'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_deployment_date'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_model_performance_logs_model_version_id'), table_name='model_performance_logs')
    op.drop_index(op.f('ix_model_performance_logs_log_date'), table_name='model_performance_logs')
    op.drop_index(op.f('ix_model_performance_logs_is_deleted'), table_name='model_performance_logs')
    op.drop_index(op.f('ix_model_performance_logs_id'), table_name='model_performance_logs')
    op.drop_table('model_performance_logs')
    # ### end Alembic commands ###
