"""Initial schema with all models

Revision ID: 3757f160fd25
Revises: 
Create Date: 2026-01-07 23:30:33.428678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3757f160fd25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=True)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_identifier_hash', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNKNOWN', name='gender'), nullable=False),
    sa.Column('has_breast_cancer_history', sa.String(length=50), nullable=True),
    sa.Column('has_family_history', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=True)
    op.create_index(op.f('ix_patients_is_deleted'), 'patients', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patients_organization_id'), 'patients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_patients_patient_identifier_hash'), 'patients', ['patient_identifier_hash'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RADIOLOGIST', 'TECHNICIAN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGE', 'VIEW', 'DOWNLOAD', 'EXPORT', 'CREATE', 'UPDATE', 'DELETE', 'ANALYZE', 'REVIEW', 'FEEDBACK', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'PERMISSION_CHANGE', 'UNAUTHORIZED_ACCESS', 'SUSPICIOUS_ACTIVITY', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.Enum('USER', 'ORGANIZATION', 'PATIENT', 'STUDY', 'IMAGE', 'ANALYSIS', 'FEEDBACK', 'SYSTEM', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.String(length=10), nullable=True),
    sa.Column('success', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=True)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('studies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=100), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('modality', sa.Enum('MG', 'US', 'MRI', 'CT', name='modality'), nullable=False),
    sa.Column('study_description', sa.String(length=500), nullable=True),
    sa.Column('referring_physician', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'ANALYZED', 'REVIEWED', 'COMPLETED', 'FAILED', name='studystatus'), nullable=False),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('comparison_available', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_accession_number'), 'studies', ['accession_number'], unique=True)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=True)
    op.create_index(op.f('ix_studies_is_deleted'), 'studies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_studies_organization_id'), 'studies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_studies_patient_id'), 'studies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    op.create_index(op.f('ix_studies_study_date'), 'studies', ['study_date'], unique=False)
    op.create_table('images',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('series_instance_uid', sa.String(length=255), nullable=True),
    sa.Column('view_type', sa.Enum('CC', 'MLO', 'ML', 'LM', 'XCCL', 'OTHER', name='viewtype'), nullable=False),
    sa.Column('laterality', sa.Enum('LEFT', 'RIGHT', 'BILATERAL', 'UNKNOWN', name='laterality'), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('bits_stored', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PREPROCESSING', 'READY', 'ANALYZED', 'FAILED', name='imagestatus'), nullable=False),
    sa.Column('preprocessing_applied', sa.String(length=500), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('artifacts_detected', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=True)
    op.create_index(op.f('ix_images_is_deleted'), 'images', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_images_laterality'), 'images', ['laterality'], unique=False)
    op.create_index(op.f('ix_images_series_instance_uid'), 'images', ['series_instance_uid'], unique=False)
    op.create_index(op.f('ix_images_sop_instance_uid'), 'images', ['sop_instance_uid'], unique=True)
    op.create_index(op.f('ix_images_status'), 'images', ['status'], unique=False)
    op.create_index(op.f('ix_images_study_id'), 'images', ['study_id'], unique=False)
    op.create_index(op.f('ix_images_view_type'), 'images', ['view_type'], unique=False)
    op.create_table('analyses',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prediction_class', sa.Enum('BENIGN', 'MALIGNANT', name='predictionclass'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('uncertainty_score', sa.Float(), nullable=True),
    sa.Column('birads_category', sa.Enum('BIRADS_0', 'BIRADS_1', 'BIRADS_2', 'BIRADS_3', 'BIRADS_4', 'BIRADS_5', 'BIRADS_6', name='biradscategory'), nullable=True),
    sa.Column('prediction_probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explainability_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roi_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('ensemble_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_birads_category'), 'analyses', ['birads_category'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=True)
    op.create_index(op.f('ix_analyses_image_id'), 'analyses', ['image_id'], unique=False)
    op.create_index(op.f('ix_analyses_is_deleted'), 'analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_analyses_model_version'), 'analyses', ['model_version'], unique=False)
    op.create_index(op.f('ix_analyses_prediction_class'), 'analyses', ['prediction_class'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('feedback',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('radiologist_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('AGREEMENT', 'CORRECTION', 'ANNOTATION', 'QUALITY_ISSUE', name='feedbacktype'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('actual_diagnosis', sa.Enum('BENIGN', 'MALIGNANT', 'UNCERTAIN', 'PENDING_BIOPSY', name='diagnosistype'), nullable=False),
    sa.Column('birads_assessment', sa.Enum('BIRADS_0', 'BIRADS_1', 'BIRADS_2', 'BIRADS_3', 'BIRADS_4', 'BIRADS_5', 'BIRADS_6', name='biradsassessment'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('findings_description', sa.Text(), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('radiologist_confidence', sa.Integer(), nullable=True),
    sa.Column('biopsy_performed', sa.Boolean(), nullable=True),
    sa.Column('pathology_result', sa.String(length=255), nullable=True),
    sa.Column('follow_up_recommendation', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['radiologist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_actual_diagnosis'), 'feedback', ['actual_diagnosis'], unique=False)
    op.create_index(op.f('ix_feedback_analysis_id'), 'feedback', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_type'), 'feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=True)
    op.create_index(op.f('ix_feedback_is_correct'), 'feedback', ['is_correct'], unique=False)
    op.create_index(op.f('ix_feedback_is_deleted'), 'feedback', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_feedback_radiologist_id'), 'feedback', ['radiologist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_radiologist_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_is_deleted'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_is_correct'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_type'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_analysis_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_actual_diagnosis'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_prediction_class'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_model_version'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_is_deleted'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_image_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_birads_category'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_images_view_type'), table_name='images')
    op.drop_index(op.f('ix_images_study_id'), table_name='images')
    op.drop_index(op.f('ix_images_status'), table_name='images')
    op.drop_index(op.f('ix_images_sop_instance_uid'), table_name='images')
    op.drop_index(op.f('ix_images_series_instance_uid'), table_name='images')
    op.drop_index(op.f('ix_images_laterality'), table_name='images')
    op.drop_index(op.f('ix_images_is_deleted'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_studies_study_date'), table_name='studies')
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_index(op.f('ix_studies_patient_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_organization_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_is_deleted'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_accession_number'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_patient_identifier_hash'), table_name='patients')
    op.drop_index(op.f('ix_patients_organization_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_is_deleted'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
