"""add_clinical_case_management_tables

Revision ID: 9fce47f24bab
Revises: f9a1d3e7b5c4
Create Date: 2026-02-22 16:50:38.492125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fce47f24bab'
down_revision: Union[str, Sequence[str], None] = 'f9a1d3e7b5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_cases',
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('backend_id', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('patient_mrn', sa.String(length=20), nullable=True),
    sa.Column('patient_first_name', sa.String(length=100), nullable=True),
    sa.Column('patient_last_name', sa.String(length=100), nullable=True),
    sa.Column('patient_dob', sa.Date(), nullable=True),
    sa.Column('patient_sex', sa.String(length=1), nullable=True),
    sa.Column('clinical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_current_step', sa.String(length=50), nullable=False),
    sa.Column('workflow_status', sa.String(length=20), nullable=False),
    sa.Column('workflow_completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('workflow_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_locked', sa.Boolean(), nullable=True),
    sa.Column('birads_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by', sa.UUID(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_hash', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backend_id')
    )
    op.create_index(op.f('ix_clinical_cases_case_number'), 'clinical_cases', ['case_number'], unique=True)
    op.create_index('ix_clinical_cases_created_by', 'clinical_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_clinical_cases_id'), 'clinical_cases', ['id'], unique=True)
    op.create_index(op.f('ix_clinical_cases_is_deleted'), 'clinical_cases', ['is_deleted'], unique=False)
    op.create_index('ix_clinical_cases_status', 'clinical_cases', ['workflow_status'], unique=False)
    op.create_table('case_findings',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('laterality', sa.String(length=1), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('radiologist_confirmed', sa.Boolean(), nullable=True),
    sa.Column('radiologist_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_findings_case_id'), 'case_findings', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_findings_id'), 'case_findings', ['id'], unique=True)
    op.create_index(op.f('ix_case_findings_is_deleted'), 'case_findings', ['is_deleted'], unique=False)
    op.create_table('case_images',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('medical_image_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('view_type', sa.String(length=10), nullable=False),
    sa.Column('laterality', sa.String(length=1), nullable=False),
    sa.Column('upload_status', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.ForeignKeyConstraint(['medical_image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_images_case_id'), 'case_images', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_images_id'), 'case_images', ['id'], unique=True)
    op.create_index(op.f('ix_case_images_is_deleted'), 'case_images', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_images_is_deleted'), table_name='case_images')
    op.drop_index(op.f('ix_case_images_id'), table_name='case_images')
    op.drop_index(op.f('ix_case_images_case_id'), table_name='case_images')
    op.drop_table('case_images')
    op.drop_index(op.f('ix_case_findings_is_deleted'), table_name='case_findings')
    op.drop_index(op.f('ix_case_findings_id'), table_name='case_findings')
    op.drop_index(op.f('ix_case_findings_case_id'), table_name='case_findings')
    op.drop_table('case_findings')
    op.drop_index('ix_clinical_cases_status', table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_is_deleted'), table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_id'), table_name='clinical_cases')
    op.drop_index('ix_clinical_cases_created_by', table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_case_number'), table_name='clinical_cases')
    op.drop_table('clinical_cases')
    # ### end Alembic commands ###
