"""Add image storage fields for upload API

Revision ID: c240aaf312d5
Revises: cead034d377f
Create Date: 2026-01-08 23:10:43.370205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c240aaf312d5'
down_revision: Union[str, Sequence[str], None] = 'cead034d377f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('patient_id', sa.String(length=100), nullable=True))
    op.add_column('images', sa.Column('study_instance_uid', sa.String(length=200), nullable=True))
    op.add_column('images', sa.Column('file_name', sa.String(length=500), nullable=True))
    op.add_column('images', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('images', sa.Column('storage_backend', sa.String(length=50), nullable=True))
    op.add_column('images', sa.Column('storage_region', sa.String(length=50), nullable=True))
    op.add_column('images', sa.Column('modality', sa.String(length=50), nullable=True))
    op.add_column('images', sa.Column('image_metadata', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('image_type', sa.String(length=100), nullable=True))
    op.add_column('images', sa.Column('view_position', sa.String(length=50), nullable=True))
    op.add_column('images', sa.Column('processing_status', sa.String(length=50), nullable=True))
    op.add_column('images', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('images', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('images', sa.Column('upload_source', sa.String(length=100), nullable=True))
    op.alter_column('images', 'study_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('images', 'view_type',
               existing_type=postgresql.ENUM('CC', 'MLO', 'ML', 'LM', 'XCCL', 'OTHER', name='viewtype'),
               nullable=True)
    op.alter_column('images', 'laterality',
               existing_type=postgresql.ENUM('LEFT', 'RIGHT', 'BILATERAL', 'UNKNOWN', name='laterality'),
               nullable=True)
    op.alter_column('images', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_images_is_deleted'), table_name='images')
    op.create_index(op.f('ix_images_patient_id'), 'images', ['patient_id'], unique=False)
    op.create_index(op.f('ix_images_study_instance_uid'), 'images', ['study_instance_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_study_instance_uid'), table_name='images')
    op.drop_index(op.f('ix_images_patient_id'), table_name='images')
    op.create_index(op.f('ix_images_is_deleted'), 'images', ['is_deleted'], unique=False)
    op.alter_column('images', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('images', 'laterality',
               existing_type=postgresql.ENUM('LEFT', 'RIGHT', 'BILATERAL', 'UNKNOWN', name='laterality'),
               nullable=False)
    op.alter_column('images', 'view_type',
               existing_type=postgresql.ENUM('CC', 'MLO', 'ML', 'LM', 'XCCL', 'OTHER', name='viewtype'),
               nullable=False)
    op.alter_column('images', 'study_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('images', 'upload_source')
    op.drop_column('images', 'uploaded_by')
    op.drop_column('images', 'deleted_at')
    op.drop_column('images', 'archived_at')
    op.drop_column('images', 'is_archived')
    op.drop_column('images', 'is_processed')
    op.drop_column('images', 'processing_error')
    op.drop_column('images', 'processing_status')
    op.drop_column('images', 'view_position')
    op.drop_column('images', 'image_type')
    op.drop_column('images', 'image_metadata')
    op.drop_column('images', 'modality')
    op.drop_column('images', 'storage_region')
    op.drop_column('images', 'storage_backend')
    op.drop_column('images', 'mime_type')
    op.drop_column('images', 'file_name')
    op.drop_column('images', 'study_instance_uid')
    op.drop_column('images', 'patient_id')
    # ### end Alembic commands ###
