"""add_model_version_id_fk_to_analyses

Revision ID: cead034d377f
Revises: 1e8539f93b11
Create Date: 2026-01-08 17:26:26.842009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cead034d377f'
down_revision: Union[str, Sequence[str], None] = '1e8539f93b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('model_version_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_analyses_model_version_id'), 'analyses', ['model_version_id'], unique=False)
    op.create_foreign_key(None, 'analyses', 'model_versions', ['model_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_index(op.f('ix_analyses_model_version_id'), table_name='analyses')
    op.drop_column('analyses', 'model_version_id')
    # ### end Alembic commands ###
